# Link repository with Travis CI
# https://travis-ci.org/

# Master branch only
branches:
  only:
    - master

# Start the databases
# See https://docs.travis-ci.com/user/database-setup/
addons:
  postgresql: "9.4"

services: 
  - postgresql
  - mysql

# Set the language
language: python
python:
  - "2.7"

before_script:
  - sudo apt-get install python-dev
#  - psql -c 'create database mimic_test;' -U postgres
#  - psql -c 'create schema mimiciii;' -d mimic_test -U postgres
#  - psql target-db -U <admin user> -p <port> -h <DB instance name> -c "\copy source-table from 'source-table.csv' with DELIMITER ','" 
#  - psql -f './buildmimic/postgres/postgres_create_tables.sql' -U postgres

# command to install dependencies
install:
  - pip install psycopg2 --quiet
  - pip install pandas --quiet
  - pip install MySQL-python --quiet
#  - pip install .
#  - pip install -r requirements.txt

# command to run tests
script: nosetests
